### ISSUE TITLE
saving last settings

### ISSUE THREAD

**Issue by DFF-fred** [Jenselme/gnome-password-generator#2]
Hi! Thank you for taking over this nice little app. 

Would it be possible to either have a setting to keep the default choices (like password length, number of generated passwords and type of password) or just have the application remember the settings last time it was launched?

Thanks.

**Comment by Jenselme** [comment]
Sure would. I was thinking of adding it. Will try to do that in the week-end.

**Comment by Jenselme** [comment]
That's  implemented. You can test it by getting the script here: https://github.com/Jenselme/gnome-password-generator/blob/save-options/gnome-password-generator.py

The button is currently called save. Not sure if it is the best name.

**Comment by DFF-fred** [comment]
Hi! I just tried, removed the "old" one, did a make & make install as per install documentation and am getting this when launching it:
Traceback (most recent call last):
  File "/usr/bin/gnome-password-generator", line 340, in do_activate
    self.main_win = MainWindow(self)
  File "/usr/bin/gnome-password-generator", line 133, in __init__
    self.load_config()
  File "/usr/bin/gnome-password-generator", line 266, in load_config
    key_file.load_from_file(self.app.CONFIG_FILE, GLib.KeyFileFlags.NONE)
GLib.Error: g-file-error-quark: No such file or directory (4)
 
Any idea what I'm missing?

**Comment by Jenselme** [comment]
Forgot to check that the configuration file exists before loading it. This is fixed.

**Comment by DFF-fred** [comment]
hehe.. no problem, working just fine now! As for the save I agree it might be confusing between saving the settings of saving the results. Not sure what to put instead thought. I ll try to think about it and get back to you if I find anything better.
Thanks a lot!

**Comment by Jenselme** [comment]
Just added a tooltip on the save button to explain what it does. Let me know what you think. If this is not enough, I may just change the text from `Save` to `Save options`.

**Comment by Jenselme** [comment]
Just released version 2.1.0 to save options. Please reopen if you have any troubles or remarks.
